apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: onyxia-tls-cert
  namespace: onyxia
spec:
  secretName: onyxia-tls-cert
  issuerRef:
   name: databrin-ca-issuer
   kind: ClusterIssuer
  dnsNames:
  - "datalab.databrin.com" 
  - "*.lab.databrin.com"
