apiVersion: v1
kind: Secret
metadata:
  name: ca-bundle
  namespace: onyxia
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIxekNDQVh5Z0F3SUJBZ0lRUUVob1BIVG9mZzlvak9DQ0NTWFpzakFLQmdncWhrak9QUVFEQWpCTE1SWXcKRkFZRFZRUUtFdzFFWVhSaFluSnBiaUJKYm1NdU1SQXdEZ1lEVlFRTEV3ZFhhV1JuWlhSek1SOHdIUVlEVlFRRApFeFprWVhSaFluSnBiaTF6Wld4bWMybG5ibVZrTFdOaE1CNFhEVEkxTVRJeU9UQTRNemN3TWxvWERUSTJNRE15Ck9UQTRNemN3TWxvd1N6RVdNQlFHQTFVRUNoTU5SR0YwWVdKeWFXNGdTVzVqTGpFUU1BNEdBMVVFQ3hNSFYybGsKWjJWMGN6RWZNQjBHQTFVRUF4TVdaR0YwWVdKeWFXNHRjMlZzWm5OcFoyNWxaQzFqWVRCWk1CTUdCeXFHU000OQpBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJeEdDdDAyWk9aR2U4WG82QzRwYlhqTitpN3hOVGplSGlLQkhVRG1vSGw1CnA3KzRLcnpKaXg2K0d6bVU4VmdlalpMRnoveDdNbUl5c3F5cGZxM1BpQnFqUWpCQU1BNEdBMVVkRHdFQi93UUUKQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCUy9Ua1AvVkJGMk50QUI3dm1EbHdWcgprL1ZXb1RBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTB2OFFtWjkyNmc1QkJJVnhYSmZ2RDdlaWZraVZLbUtMClQ4NUJQU09zSkg0Q0lRRFd6bTlXREtTL0hKM0hCZzd0SThyaXVJcnJETzJObitzUktlcnpVVlFwMkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgo= 

